spring:
  application:
    name: test
  security:
    oauth2:
      resourceserver:
        jwt:
          # issuer-uri: http://localhost:8800/auth/realms/myrealm
          # jwk-set-uri: http://localhost:8800/auth/realms/myrealm/protocol/openid-connect/certs
          issuer-uri: http://128.199.164.171:8800/auth/realms/myrealm
          jwk-set-uri: https://128.199.164.171:9443/auth/realms/myrealm/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://128.199.164.171:8800/auth
  realm: myrealm
  resource: login-app
  public-client: true
  security-constraints:
    - authRoles: [user]
      securityCollections:
        - name: api-testing
          patterns: ["/api/test"]
  principal-attribute: preferred_username

server:
  port: 8081
