server:
  port: 8081

spring:
  application:
    name: test
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://saintrivers.tech:9443/auth/realms/myrealm
          jwk-set-uri: https://saintrivers.tech:9443/auth/realms/myrealm/protocol/openid-connect/certs
